name: adf_v0.1
channels:
  - conda-forge
  - defaults
dependencies:
  - pyyaml=6.0
  - scipy=1.10.0
  - cartopy=0.21.1
  - netcdf4=1.6.2
  - xarray=2023.1.0
  - matplotlib
  - pandas=1.5.3
  - pint=0.16   #GeoCAT doesn't work with newer versions
  - xskillscore=0.0.5
  - geocat-comp=2022.08.0
  - python=3.11
prefix: /glade/u/home/brianpm/miniconda3/envs/adf_v0.1
